const Constants = {
    // GOOGLE_API_KEY : "AIzaSyC-pVwrjOD-NBZ97TFRMTlMmr4VwbsAZHA",
    GOOGLE_API_KEY : "AIzaSyBYmax9vtNdT6aRZVBw65oDtjVFwDce0nE",
    PLATFORM_ANDROID : "android",
    PLATFORM_IOS : "ios",
    SAVE_ACCESS_TOKEN : "save_token",
    USER_MODEL : "user_model",
    EMAIL_REGEX : /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
    PHONE_NUMBER_REGEX : /^((0|[1-9]).[0-9]+)$/,
    SOCKET_UPDATE_RUNNER_LOCATION_EMIT : "socket_emit",
    SOCKET_UPDATE_USER_LOCATION_EMIT : "socket_update",
    DEVICE_TOKEN : "device_token",
    PERSIST_SIGN_UP_DATA_MODEL : "persist_sign_up_data_model",
    BOOKING_DETAILS_RUNNERS : "booking_details_runners",
    CHAT_DETAIL_STORE_KEY : "booking_chat_detail",
    BOOKING_STATUS_ACCEPTED : "accepted",
    BOOKING_TYPE : "Booking Accepted",  
    BOOKING_STATUS_STARTED : "started",
    BOOKING_STATUS_CANCELLED : "canceled",
    BOOKING_STATUS_COMPLETED : "completed",
    PRODUCT_ITEM_LIST : "itemList",
    CURRENT_BOOKING_STATUS : "current_booking-status",
    BOOKING_ID : "booking_id",
    SERVICE_START_TIME : "service_start_time",
    MESSAGE_TYPE_NOTIFICATION: "Message",
    SERVICE_ACCEPT_TIME : "service_accept_time",
    SERVICE_END_TIME : "service_end_time",
    TIME_FORMAT : "hh:mm",
    MERIDIEN_TIME_FORMAT : "HH",
    DATE_FORMAT : "MMMM Do YYYY, hh:mm A",
    LATITUDE : 0,
    LONGITUDE : 0,
    LATITUDE_DELTA : 0.0922,
    markerIDs : ["MarkerOrigin", "MarkerDestination"],
    TIME_FORMAT_CHAT : "h:mm A"
};
export default Constants;

