const color = {
    THEME_COLOR_BLUE : "#60DEE3",
    THEME_COLOR_GRAY : "#878787",
    THEME_COLOR_BLACK : "#393939",
    THEME_COLOR_BLACK_DARK : "#000000",
    THEME_COLOR_WHITE : "#FFFFFF",
    THEME_COLOR_ACTIVE_TAB : "#EE4F56",
    THEME_COLOR_LIGHT_GRAY : "#F6F6F6",
    THEME_COLOR_LIGHT_GRAY_SHADE : "#F1F1F1",
    THEME_COLOR_GRAY_HOME_BG : "#FBFBFB",
    THEME_PROGRESS_LINE_COLOR : "#EBEBEB",
    THEME_COLOR_GREEN : "#6BE5A7",
    TEXT_COLOR_DARK : "#000000",
    TEXT_COLOR_LIGHT : "#FFFFFF",
    TEXT_COLOR_COLORED : "#60DEE3",
    TEXT_COLOR_RED : "#EE4F56",
    TEXT_COLOR_GRAY : "#EE4F56",
    THEME_UNSELECTED_ITEM : "#F2F2F2",
    HEADER_BOTTOM_LINE_COLOR : "#BDBDBD",
    LOADER_COLOR_GRAY : "rgb(119, 119, 119)"
};

export default color;
