const ActionTypes = {
    RESTORE_TOKEN_KEY : "RESTORE_TOKEN",
    SIGN_IN_KEY : "SIGN_IN",
    SIGN_OUT_KEY : "SIGN_OUT",
    UPDATE_RUNNER_LOCATION_SUCCESS : "update_runner_location_success",
    ACCEPTED_BOOKING : "ACCEPTED_BOOKING",
    NEW_MESSAGE : "MESSAGE_ACTION",
    NEW_MESSAGE_AVAILABLE : "NEW_MESSAGE_AVAILABLE",
    NETWORK_STATE:"NETWORK_STATE",
    LOGOUT : "LOGOUT"

};
export default ActionTypes;

